---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-projects-claim
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce  # Ensure this matches the PV
  resources:
    requests:
      storage: 2Gi
  storageClassName: awx-projects-volume  # Must match PV
  volumeMode: Filesystem



