---
- name: Check date and time on Windows Server
  hosts: windows
  gather_facts: no
  tasks:
    - name: Get current date and time
      win_command: "powershell -Command Get-Date"
      register: datetime_output

    - name: Display date and time
      debug:
        msg: "Current date and time on {{ inventory_hostname }}: {{ datetime_output.stdout }}"

